OK_Django_Test/OK_Django_Test/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include
import xadmin
from django.views.static import serve
from OK_Django_Test import settings
urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path('',include(('blog.urls','blog'),namespace='Blog')),

    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

OK_Django_Test/apps/blog/urls.py
from  django.urls import path,include,re_path
from . import views



urlpatterns = [

   # path('',views.Index_View.as_view()),
    path('index/',views.Index_View.as_view(),name = 'index'),
    path('Blog/',views.Blog_view_None.as_view(),name = 'Blog'),
    path('Blog/<int:pk>/',views.Blog_view.as_view(),name = 'Blog'),
    path('sw/',views.sw_view.as_view(),name = 'sw'),
    path('art/',views.testView.as_view() ,name= 'art'),
    path('about/',views.aboutView.as_view() ,name= 'about'),
    path('',views.Index_View.as_view(),name = 'index_view'),
    path('login/',views.login_load),
    path('logout/',views.logout_load,name="dsds"),
   # re_path('[\s\S]*?/comment',views.comment,name='me'),
]

OK_Django_Test/extra_apps/xadmin/xadmin/xadmin/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),

]

OK_Django_Test/apps/blog/models.py
from django.db import models
import  time
from  django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class Article(models.Model):
    time = models.DateTimeField(default=timezone.now,verbose_name='时间')
    read_sum = models.IntegerField(default=0,verbose_name='阅读数量',blank=True,null=True)
    like_sum = models.IntegerField(default=0,verbose_name='点赞数',blank=True)
    title = models.CharField(max_length=20,default=None,verbose_name='标题')
    name = models.CharField(max_length=20,default=None,verbose_name='文章题目')
    theme = models.CharField(max_length=10,verbose_name='主题')
    author = models.CharField(max_length=5,default="何泽君",verbose_name='作者')
    write_sum = models.IntegerField(verbose_name='字数')
    text = models.TextField(verbose_name="内容",default=None)
    update_text = models.CharField(max_length=50,verbose_name='更新内容',blank=True,null=True)

    def __str__(self):
        return  self.title

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name
        ordering =['-time']


class Commets(models.Model):
    comment_sum = models.IntegerField(default=0,verbose_name='评论量')
    time = models.DateTimeField(default=timezone.now,verbose_name='评论时间')
    commenter = models.CharField(max_length=20,verbose_name='评论人员')
    text = models.TextField(verbose_name="内容",default=None)
    name = models.CharField(max_length=20,default=0,verbose_name='别名')
    mail = models.EmailField(max_length=20,verbose_name='邮箱',default=0)

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = verbose_name
        ordering = ['-time']


    def __str__(self):
        return self.commenter

class Users(User):
    Can_reader = models.CharField(max_length=3,verbose_name="是否可以使用权限")


class Study_Sort(models.Model):
    name = models.CharField(max_length=20,verbose_name='分类名称')
    image = models.ImageField(upload_to='img',default='/img/5.jpg',verbose_name="上传图片")
    study_tag = models.CharField(max_length=10,verbose_name='标签',default=None)
    study_tag_two = models.CharField(max_length=10,verbose_name='标签1',default=None)
    study_tag_three = models.CharField(max_length=10,verbose_name='标签2',default=None)
    study_fire = models.IntegerField(default=0,verbose_name='学习热度')
    time = models.DateTimeField(default=timezone.now,verbose_name="制定时间")
    YEAR_IN_SCHOOL_CHOICES = (
        ('web开发', 'web开发'),
        ('网络安全', '网络安全'),
        ('爬虫', '爬虫'),
        ('自然语言处理', '自然语言处理'),
    )
    study_tag_select = models.CharField(choices=YEAR_IN_SCHOOL_CHOICES,max_length=20,default=0,verbose_name='标签')
    class Meta():
        verbose_name = "学习分类"
        verbose_name_plural = verbose_name
        ordering = ['-time']


    def __str__(self):
        return self.name




class abou_test(models.Model):
    name = models.CharField(max_length=20,default='')
    link = models.CharField(max_length=100,default='#')
    time = models.DateTimeField(default = timezone.now)


    class Meta():
        verbose_name = '关于'
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name
#artical
#update

OK_Django_Test/apps/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
import logging
import json
# Create your views here.
from django.views.generic import ListView,DetailView,TemplateView
from  .models import  Article,Commets,Users,Study_Sort,abou_test
from  django.contrib.auth import authenticate,login,logout
import  markdown
from django.utils import timezone


def login_load(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username= username,password=password)

        if user is not None:
            login(request,user)
            return_json = {'result':1}
            request.session['name'] = username
            return HttpResponse(return_json['result'])
        else:
            print("登陆错误")
            return_json = {'result': 2}
            return HttpResponse(return_json['result'])

    else:
        return render(request, "blog/index.html")


def logout_load(request):
    logout(request)
    request.session['name'] = None
    return render(request, "blog/index.html")



def comment(request):
    comment_all = Commets.objects.all()
    if request.method == 'POST':
        name = request.POST['name_body']
        mail = request.POST['mail']
        v_name = request.POST['v_name']
        comment = request.POST['comment']
        comment_all.create(name=name,mail=mail,commenter=v_name,text=comment,time=timezone.now,comment_sum=len(comment))
        return  render(request,'/')
    else:
        return render(request,'blog/index.html')


class Index_View(ListView):
    model  = Article
    template_name = 'blog/index.html'
    context_object_name = 'articals'
    extra_context = {'articalss':Article.objects.all()[3:6],'updates':Article.objects.all()[:4]}


    def get_queryset(self):
        articals = Article.objects.all()[:3]
        return articals




class Blog_view(DetailView):
    model = Article
    template_name = 'blog/Blog.html'
    context_object_name = 'artical_list'

    pk_url_kwarg = 'pk'



    def get_object(self, queryset=None):
        artical_list = super(Blog_view,self).get_object(queryset=None)
        artical_list.text = markdown.markdown(artical_list.text,
                                      extensions=[
                                          'markdown.extensions.extra',
                                          'markdown.extensions.codehilite',
                                          'markdown.extensions.toc',
                                      ])
        return artical_list







class Blog_view_None(ListView):
    template_name = 'blog/Blog.html'
    model = Article
    context_object_name = 'artical_list'

    def get_queryset(self):
        artical_list = Article.objects.get(name='欢迎来到我的博客')
        return artical_list


class sw_view(ListView):
    model = Article
    template_name = 'blog/SofeWare_load.html'
    context_object_name = 'artitcals'


class testView(ListView):
    model = Study_Sort
    template_name = 'blog/art_test.html'
    context_object_name = 'object'

    def get_queryset(self):
        object = Study_Sort.objects.all()
        return object



class artView(ListView):
    model = Study_Sort
    template_name = 'blog/art_test.html'
    context_object_name = 'object'

    def get_queryset(self):
        object = Study_Sort.objects.all()[:3]
        return object




class aboutView(ListView):
    model = abou_test
    template_name = 'blog/about.html'
    context_object_name = 'object'
    extra_context = {'object_two':abou_test.objects.all()[6:abou_test.objects.all().count()]}

    def get_queryset(self):
        object = abou_test.objects.all()[:6]
        return  object

OK_Django_Test/templates/blog/Blog.html
<!DOCTYPE html>
{% load  staticfiles %}
<html>

	<head>
		<meta charset="utf-8" />
		<title></title>
	</head>
	<script src="{% static 'js/jquery-3.3.1.min.js' %}" type="text/javascript" charset="utf-8"></script>
	<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript" charset="utf-8"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.css' %}" />

	<style type="text/css">
		ul{
			list-style: none;
		}
	</style>
	<body>
		        {% include 'blog/base/header.html' %}
		
		
		<div class="container">
			<hr class="divider" />
			<div class="row ">
				<div class="col-md-3 hidden-sm ">
					<h3>目录</h3>
					<img src="{% static 'img/shouye/timg.jpg' %}" width="250px" height="200px" />
			<!--		<ul>
						<li>Django之美丽的Admin</li>
					</ul>
					<ul class="col-md-offset-2  ">
						<li>前言</li>
						<li>下载我们的xadmin</li>
					</ul>-->
				</div>
				<div class="col-md-9" >
					<h1>{{ artical_list.title }}</h1>
					<span class="">{{ artical_list.theme }}</span>
					<span class="">{{ artical_list.time }}</span>
					<span class="">阅读({{ artical_list.read_sum }})</span>
					<span class="">喜欢({{ artical_list.like_sum }})</span>
					<div style="width: 20px;height: 20px;"></div>
					<div class="entry-content clearfix">
						{{ artical_list.text|safe }}

					</div>
					<hr class="divider" />

				
			</div>
				
				
				
			</div>

			</div>
			
			<hr class="divider" />

		{% include 'blog/base/base.html' %}



	</body>
</html>

OK_Django_Test/templates/blog/SofeWare_load.html
<!DOCTYPE html>
{% load  staticfiles %}
<html>

	<head>
		<meta charset="utf-8" />
		<title></title>
	</head>
	<script src="{% static 'js/jquery-3.3.1.min.js' %}" type="text/javascript" charset="utf-8"></script>
	<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript" charset="utf-8"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.css' %}" />

	<body>
		        {% include 'blog/base/header.html' %}




		<div class="container">
			{% for artictcal in artitcals %}
                <div class="row">
				<div class="list-group">
					<p class="list-group-item-info"><h1><a href="{% url 'Blog:Blog' artictcal.id %}">{{ artictcal.title }}</a></h1></p>
					<h5 class="list-group-item-heading">{{ artictcal.time }}</h5>
					<span class="list-group-item-text">{{ artictcal.text|truncatechars:250 }}</span>
				</div>
			</div>
            			{% endfor %}



			
			<div class="row">
				<div class="col-md-12 text-center">
														<nav aria-label="Page navigation">
  <ul class="pagination pagination-lg">
    <li>
      <a href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li class="disabled"><a href="#" class="disabled">1</a></li>
    <li class="active"><a href="#" >2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li>
      <a href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>ls
</nav>
					
				</div>
			</div>
			
		</div>

		 {% include 'blog/base/base.html' %}
	</body>
</html>

OK_Django_Test/templates/blog/about.html
<!DOCTYPE html>
{% load  staticfiles %}
<html>

	<head>
		<meta charset="utf-8" />
		<title></title>
	</head>
	<script src="{% static 'js/jquery-3.3.1.min.js' %}" type="text/javascript" charset="utf-8"></script>
	<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript" charset="utf-8"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.css' %}" />
	<script type="text/javascript" src="{% static 'js/tagcloud.js' %}"></script>
	<style type="text/css">
		.fl {
			float: left;
		}
		
		.fr {
			float: right;
		}
		
		.wrapper {
			width: 1200px;
			height: 300px;
			margin: 0 auto;
		}
		
		.wrapper p {
			padding-top: 150px;
			line-height: 27px;
			color: #999;
			font-size: 14px;
			text-align: center;
		}
		
		.tagcloud {
			position: relative;
			margin-top: -150px;
		}
		
		.tagcloud a {
			position: absolute;
			top: 0;
			left: 0;
			display: block;
			padding: 11px 30px;
			color: #333;
			font-size: 16px;
			border: 1px solid #e6e7e8;
			border-radius: 18px;
			background-color: #f2f4f8;
			text-decoration: none;
			white-space: nowrap;
			-o-box-shadow: 6px 4px 8px 0 rgba(151, 142, 136, .34);
			-ms-box-shadow: 6px 4px 8px 0 rgba(151, 142, 136, .34);
			-moz-box-shadow: 6px 4px 8px 0 rgba(151, 142, 136, .34);
			-webkit-box-shadow: 6px 4px 8px 0 rgba(151, 142, 136, .34);
			box-shadow: 6px 4px 8px 0 rgba(151, 142, 136, .34);
			-ms-filter: "progid:DXImageTransform.Microsoft.Shadow(Strength=4,Direction=135, Color='#000000')";
			/*兼容ie7/8*/
			filter: progid:DXImageTransform.Microsoft.Shadow(color='#969696', Direction=125, Strength=9);
			/*strength是阴影大小，direction是阴影方位，单位为度，可以为负数，color是阴影颜色 （尽量使用数字）使用IE滤镜实现盒子阴影的盒子必须是行元素或以行元素显示（block或inline-block;）*/
		}
		
		.tagcloud a:hover {
			color: #3385cf;
		}
	</style>

	<body>
		        {% include 'blog/base/header.html' %}

		<div class="container">

			<div class="row">
				<div class="wrapper hidden-sm">
					<p>Go to<br/>The label you like </p>
					<div class="tagcloud fl ">
                        {% for foo in object %}



						<a href="{{foo.link }}">{{ foo.name }}</a>


                        {% endfor %}
                        

                        
					</div>
					<div class="tagcloud fr">
                        {% for foo in object_two %}
                        <a href="{{ foo.link  }}">{{ foo.name }}</a>
                        {% endfor %}
                        

					</div>
				</div>
				<!--wrapper-->
			</div>
			<div style="width: 20px;height: 20px;"></div>
			<hr class="divider" />
			<div style="width: 200px;height: 100px;"></div>
			
			<div class="row">
				<div class="col-md-8 col-sm-8">
					<div class="text-center">
						<h2 style="color: red;"><b>尝试与回报</b></h2>
						<p><h3>The great pleasure in life is doing what people say you cannot do.</h3> </p>
						<p><h3>人生最大的快乐是做到别人认为你做不到的事情。</h3></p>
						<p>
							<a href="/index/">Read for me</a>
						</p>
					</div>
				</div>
				<div class="col-md-4 col-sm-4">
					<div class="text-center ">
						<h2>联系方式</h2>
						<p>QQ:1097690268</p>
						<p>Mail:1097690268@qq.com</p>
						<p>Github:https://github.com/Alpaca-H</p>
					</div>

				</div>

			</div>
		</div>
		
		<div style="width: 200px;height: 100px;"></div>
		 {% include 'blog/base/base.html' %}

		<script type="text/javascript">
			/*3D标签云*/
			tagcloud({
				selector: ".tagcloud", //元素选择器
				fontsize: 16, //基本字体大小, 单位px
				radius: 100, //滚动半径, 单位px
				mspeed: "normal", //滚动最大速度, 取值: slow, normal(默认), fast
				ispeed: "normal", //滚动初速度, 取值: slow, normal(默认), fast
				direction: 100, //初始滚动方向, 取值角度(顺时针360): 0对应top, 90对应left, 135对应right-bottom(默认)...
				keep: false //鼠标移出组件后是否继续随鼠标滚动, 取值: false, true(默认) 对应 减速至初速度滚动, 随鼠标滚动
			});
		</script>
	</body>

</html>

OK_Django_Test/templates/blog/contact.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
	</head>
	<script src="{% static 'js/jquery-3.3.1.min.js' %}" type="text/javascript" charset="utf-8"></script>
	<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript" charset="utf-8"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.css' %}" />
	<body>

        {% include 'blog/base/header.html' %}
		
		<div class="container">
			<div class="row text-center">
				<h1>小站刚刚建立,欢迎大家提出问题和建议</h1>
				
				
				<textarea name="textarea" rows="" cols="" style="width: 600px;height: 400px;"></textarea>
				<br />
				<input type="submit" name="" id="" class="btn btn-success " value="发送" />
				<div style="width: auto; height: 250px;"></div>
			</div>
			
		</div>
		 {% include 'blog/base/base.html' %}

	</body>
</html>

OK_Django_Test/templates/blog/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

	<head>
		<meta charset="utf-8" />
		<title></title>
	</head>
	<script src="{% static 'js/jquery-3.3.1.min.js' %}" type="text/javascript" charset="utf-8"></script>
	<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript" charset="utf-8"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.css' %}" />


	<body>
        {% include 'blog/base/header.html' %}

		<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
			<!-- Indicators -->
			<ol class="carousel-indicators">
				<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
				<li data-target="#carousel-example-generic" data-slide-to="1"></li>
				<li data-target="#carousel-example-generic" data-slide-to="2"></li>
			</ol>

			<!-- Wrapper for slides -->
			<div class="carousel-inner" role="listbox">
				<div class="item active">
					<img src="{% static 'img/shouye/绿色.jpg' %}" style="opacity: 0.8;" class="first_slide" alt="first_slide">
					<div class="carousel-caption">
						<h1>如果你有更好的宽屏贴图</h1>
						<h1>请联系我</h1>
					</div>
				</div>
				<div class="item">
					<img src="{% static 'img/shouye/蓝色.jpg' %}" alt="seconde_slide" class="seconde_slide">
					<div class="carousel-caption">
						<h1>这里是Alpaca的</h1>
						<h1>个人网站</h1>
					</div>
				</div>
				<div class="item">
					<img src="{% static 'img/shouye/黄色.jpg' %}" alt="third_slide" class="third_slide">
					<div class="carousel-caption">
						<h1>欢饮参观</h1>
					</div>
				</div>
			</div>

			<!-- Controls -->
			<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
				<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
			</a>
			<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
				<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				<span class="sr-only">Next</span>
			</a>
		</div>
		<hr  class="divider"/>
		
		
		

		<div class="container marketing">
			
					<!--
        	作者：Alpac
        	时间：2018-05-20
        	描述：body2
        -->
			
			<div class="row">
        		<div class="col-md-8">
                    <div class="row">
                        {% for artical in articals %}
                            <div class="col-md-4">
        				        <h3 class="text-danger">{{ artical.title }}</h3>
        				        <p>{{ artical.text|truncatechars:100 }}</p>
        				        <p><a href="{% url 'Blog:Blog' artical.id %}">Read for me</a></p>
        			        </div>
                        {% endfor %}
                    </div>
                    <div class="row">
                        {% for artical in articalss %}
                            <div class="col-md-4">
        				        <h3 class="text-danger">{{ artical.title }}</h3>
        				        <p>{{ artical.text|truncatechars:100 }}</p>
        				      <p><a href="{% url 'Blog:Blog' artical.id %}">Read for me</a></p>
        			        </div>
                        {% endfor %}
                    </div>
                </div>
        		<div class="col-md-4">
        			<ul class="list-group">
        				<li class="list-group-item list-group-item-info">更新内容</li>
        				{% for  update in updates %}
                            <li class="list-group-item">
        					    <h4 class="list-group-item-heading">{{ update.author }}创建了一个{{ update.title }}</h4>
        					    <p class="list-group-item-text">主题是{{ update.theme }} </p>
                                <P class="list-group-item-heading">{{ update.time }}</P>
        				    </li>
                        {% endfor %}
        			</ul>
        		</div>
        	</div>
        	
        	
        	<hr class="divider" />
					
				<!--
       	作者：
       	时间：2018-05-20
       	描述：body3
       -->
			
			{% for friend in friends  %}
                <div class="row">
				<div class="col-md-3">
					<img src="{% static 'img/shouye/头像.jpg' %}" width="100px" height="100px"/>
				</div>
				<div class="col-md-9">
					<p>一个专注于python开发的小程序员</p>
					<p>Django开发，Flask开发，人工智能等小内容</p>
					<input type="submit" name="" id="" value="Look" class="col-md-offset-8 btn btn-danger btn-sm" />
				</div>
			</div>
			<hr class="divider" />
			{% endfor %}



		<!--
        	作者：Alpaca
        	时间：2018-05-20
        	描述：一些话
        -->
			<div class="row">
				<h1 style="text-align: center;" class="text-info">You Can Up</h1>
				<p style="text-align: center;">You Can Up</p>
			</div>
			

		</div>


    {% include 'blog/base/base.html' %}

	</body>

</html>

OK_Django_Test/templates/blog/tag.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>无标题文档</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>3D标签云</title>
  <script type="text/javascript" src="js/tagcloud.js"></script>
  <style type="text/css">
    .fl{ float: left; }
    .fr{ float: right; }
    .wrapper{ width: 1200px; height: 300px; margin: 0 auto; }
    .wrapper p{ padding-top: 150px; line-height: 27px; color: #999; font-size: 14px; text-align: center;  }
    .tagcloud { position: relative; margin-top:-150px; }
    .tagcloud a{ position: absolute;  top: 0; left: 0;  display: block; padding: 11px 30px; color: #333; font-size: 16px; border: 1px solid #e6e7e8; border-radius: 18px; background-color: #f2f4f8; text-decoration: none; white-space: nowrap;
      -o-box-shadow: 6px 4px 8px 0 rgba(151,142,136,.34);
      -ms-box-shadow: 6px 4px 8px 0 rgba(151,142,136,.34);
      -moz-box-shadow: 6px 4px 8px 0 rgba(151,142,136,.34);
      -webkit-box-shadow: 6px 4px 8px 0 rgba(151,142,136,.34);
      box-shadow: 6px 4px 8px 0 rgba(151,142,136,.34);
      -ms-filter:"progid:DXImageTransform.Microsoft.Shadow(Strength=4,Direction=135, Color='#000000')";/*兼容ie7/8*/
      filter: progid:DXImageTransform.Microsoft.Shadow(color='#969696', Direction=125, Strength=9);
      /*strength是阴影大小，direction是阴影方位，单位为度，可以为负数，color是阴影颜色 （尽量使用数字）使用IE滤镜实现盒子阴影的盒子必须是行元素或以行元素显示（block或inline-block;）*/
    }
    .tagcloud a:hover{ color: #3385cf; }
  </style>
</head>
<body>

<div class="wrapper">
    <p>没有发现任何关注内容<br/>此处为您显示检索历史</p>
    <div class="tagcloud fl">
      <a href="#">文献综述</a>
      <a href="#">对外投资</a>
      <a href="#">机器人</a>
      <a href="#">区块链</a>
      <a href="#">科技创新</a>
      <a href="#">计算机科学</a>
      <a href="#">自动驾驶</a>
      <a href="#">研究价值</a>
      <a href="#">模式识别</a>
      <a href="#">自然语言处理</a>
    </div>
    <div class="tagcloud fr">
      <a href="#">大数据时代</a>
      <a href="#">一带一路</a>
      <a href="#">智能控制</a>
      <a href="#">人工智能神经网络</a>
      <a href="#">计算机科学</a>
      <a href="#">自动驾驶</a>
    </div>
</div><!--wrapper-->

<script type="text/javascript">
    /*3D标签云*/
    tagcloud({
        selector: ".tagcloud",  //元素选择器
        fontsize: 16,       //基本字体大小, 单位px
        radius: 100,         //滚动半径, 单位px
        mspeed: "normal",   //滚动最大速度, 取值: slow, normal(默认), fast
        ispeed: "normal",   //滚动初速度, 取值: slow, normal(默认), fast
        direction: 135,     //初始滚动方向, 取值角度(顺时针360): 0对应top, 90对应left, 135对应right-bottom(默认)...
        keep: false          //鼠标移出组件后是否继续随鼠标滚动, 取值: false, true(默认) 对应 减速至初速度滚动, 随鼠标滚动
    });
</script>
</body>
</html>