hzj_test/apps/courses/urls.py
# -*- coding:utf-8 -*-
__author__ = 'hzj'


from django.urls import path,include
from courses.views import courselistView,coursecommentView,coursedetailView,coursevideoView

app_name = 'courses'
urlpatterns = [
    path('list/',courselistView.as_view(),name="courses-list"),
    path('course-detai/<int:course_id>', coursedetailView.as_view(), name='course_detail'),
    path('course-comment/<int:course_id>', coursecommentView.as_view(), name='course_comment'),
    path('course-video/<int:course_id>', coursevideoView.as_view(), name='course_video')
]

hzj_test/apps/organization/urls.py
# -*- coding:utf-8 -*-
__author__ = 'hzj'


from django.urls import path,include
from .views import OrgView,Add_UseAsk,\
    Teacher_detail,Teacher_list,org_detail_homepage,\
    org_detail_course,org_detail_desc,org_detail_teachers


app_name = "organization"
urlpatterns = [
    path('org-list',OrgView.as_view(),name="org_list"),
    path('Add_UseAsk/',Add_UseAsk.as_view(),name = "add_useask"),
    path('teacher_datil/',Teacher_detail.as_view(),name= "detail"),
    path('teacher_list/',Teacher_list.as_view(),name = "list"),
    path('org-detail-homepage/<int:org_id>',org_detail_homepage.as_view(),name='detail_homepage'),
    # path('org-detail-homepage/', org_detail_homepage.as_view(), name='detail_homepage'),
    path('org-detail-course/<int:org_id>', org_detail_course.as_view(), name='detail_course'),
    path('org-detail-desc/<int:org_id>', org_detail_desc.as_view(), name='detail_desc'),
    path('org-detail-teachers/<int:org_id>', org_detail_teachers.as_view(), name='detail_teachers')

]

hzj_test/hzj_test/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
import xadmin
from django.views.generic import TemplateView,ListView,DetailView
from users.views import Login_View,logout_te,registerview,activeView,ForgetPassword,updatePassword
from organization.views import OrgView

from django.views.static import serve
from hzj_test.settings import MEDIA_ROOT

urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path('',TemplateView.as_view(template_name='index.html'),name = "index"),

    path('login/',Login_View.as_view(),name = 'login'),

    path('logout/',logout_te.as_view(),name = 'logout'),

    path('register/',registerview.as_view(),name='register'),

    re_path('active/(?P<active_code>.*)/$',activeView.as_view(),name="activeView"),

    path('forget_password/',ForgetPassword.as_view(),name="forget_password"),

    re_path('get_password/(?P<password>.*)/$',updatePassword.as_view(),name='updatePassword'),

    re_path(r'^captcha/', include('captcha.urls')),


    re_path('media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT }),


    path('org-list/',include('organization.urls',namespace="org")),

    path('course/',include('courses.urls',namespace='courses')),


    path('usercenter-info/',include('operation.urls',namespace='operation'))

]

hzj_test/templates/course-list.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>公开课列表 - 慕学在线网</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <script src="{% static 'js/jquery.min.js'%}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js'%}" type="text/javascript"></script>

</head>
<body>
<section class="headerwrap ">
    <header>
		<div  class=" header">
 			<div class="top">
				<div class="wp">
					<div class="fl"><p>服务电话：<b>33333333</b></p></div>
					<!--登录后跳转-->

                        
                        <div class="personal">
                            <dl class="user fr">
                                <dd>bobby<img class="down fr" src="../images/top_down.png"/></dd>
                                <dt><img width="20" height="20" src="../media/image/2016/12/default_big_14.png"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="../media/image/2016/12/default_big_14.png"/></dt>
	                                <dd>
	                                    <h2>django</h2>
	                                    <p>bobby</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="personcenter fl" href="usercenter-info.html">进入个人中心</a>
	                                <a class="fr" href="/logout/">退出</a>
                                </div>
                            </div>
                        </div>
                        <a href="usercenter-message.html">
                            <div class="msg-num"> <span id="MsgNum">0</span></div>
                        </a>
                    


				</div>
			</div>

            <div class="middle">
                <div class="wp">
                    <a href="index.html"><img class="fl" src="../images/logo.jpg"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课老师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="../images/search_btn.png"/>
                    </div>
                </div>
            </div>
            
            
			<nav>
				<div class="nav">
					<div class="wp">
						<ul>
							<li ><a href="index.html">首页</a></li>
							<li class="active">
								<a href="course-list.html">
									公开课<img class="hot" src="../images/nav_hot.png">
								</a>
							</li>
							<li >
								<a href="teachers-list.html">授课教师</a>
							</li>
							<li ><a href="org-list.html">授课机构</a></li>
						</ul>
					</div>
				</div>
			</nav>
            
			</div>
    </header>
</section>
<!--crumbs start-->

    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="index.html">首页</a>></li>
                <li>公开课</li>
            </ul>
        </div>
    </section>


    <section>
	<div class="wp">
		<div class="list" style="margin-top:0;">
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li class="active"><a href="?sort=">最新 </a></li>
						<li ><a href="?sort=hot">最热门</a></li>
						<li ><a href="?sort=students">参与人数</a></li>
					</ul>
				</div>
                <div id="inWindow">
                    <div class="tab_cont " id="content">
					<div class="group_list">
                        {% for course in courses.object_list %}
                            <div class="box">
                                <a href="{% url 'courses:course_detail' course.id %}">
                                    <img width="280" height="350" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="course-detail.html">
                                        <h2>{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">时长：<i class="key">{{ course.datetime }}</i></span>
                                    <span class="fr">学习人数：{{ course.students}}&nbsp;&nbsp;</span>
                                </div>
                                <div class="bottom">
                                    <a href="course-detail.html"><span class="fl">{{ course.course_org }}</span></a>
                                    <span class="star fr notlogin" data-favid="15">
                                        {{ course.fav_nums }}
                                    </span>
                                </div>
                            </div>

                        {% endfor %}


					</div>
                    <div class="pageturn">
                        <ul class="pagelist">
                                        <li class="active"><a href="?page=1">1</a></li>
                                        <li><a href="?page=2" class="page">2</a></li>
                                <li class="long"><a href="?page=2">下一页</a></li>
                            

                        </ul>
                    </div>
				</div>
                </div>
			</div>
			<div class="right layout">
				<div class="head">热门课程推荐</div>
				<div class="group_recommend">
                {% for hot_course in hot_courses %}
                    <dl>
						<dt>
							<a target="_blank" href="">
								<img width="240" height="220" class="scrollLoading" src="{{ MEDIA_URL }}{{ hot_course.image }}"/>
							</a>
						</dt>
						<dd>
							<a target="_blank" href=""><h2>{{ hot_course.course_org }}</h2></a>
							<span class="fl">难度：<i class="key">{{ hot_course.degree }}</i></span>
						</dd>
					</dl>
                {% endfor %}

				</div>
			</div>
		</div>
	</div>
</section>

<footer>
		<div class="footer">
			<div class="wp">
				<ul class="cont">
					<li class="logo"><a href=""><img src="../images/footlogo.png"/></a></li>
					<li class="code"><img src="../images/code.jpg"/><p class="center">扫描关注微信</p></li>
					<li class="third"><img class="fl" src="../images/tell.png"/><p class="tell">33333333</p><p class="time">周一至周日 9:00-18:00</p></li>
				</ul>

			</div>
			<p class="line"></p>
			<div class="wp clear">
                <span class="fl">? 2016 www.projectsedu.com 慕学在线-在线学习交流平台 保留所有权利</span>
                <span class="fr">copyright ? 2016 ICP备案证书号：蜀ICP备xxxxx号-1</span>
			</div>
		</div>
	</footer>

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<script src="{% static 'js/selectUi.js'%}" type='text/javascript'></script>
<script src="{% static 'js/deco-comment.js'%}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js'%}"></script>
<script src="{% static 'js/plugins/layer/layer.js'%}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js'%}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js'%}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js'%}"  type="text/javascript"></script>
<script src="{% static 'js/deco-common.js'%}"  type="text/javascript"></script>

</body>
</html>

hzj_test/templates/org-detail-desc.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>机构首页</title>
	<link rel="stylesheet" type="text/css" href="{%static 'css/reset.css'%}">
	<link rel="stylesheet" type="text/css" href="{%static 'css/animate.css'%}">
	<link rel="stylesheet" type="text/css" href="{%static 'css/style.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'js/plugins/queryCity/css/cityLayout.css'%}">

    <script src="{%static 'js/jquery.min.js'%}.js" type="text/javascript"></script>
    <script src="{%static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    
</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
		<div  class="header2 header">
 			
                <div class="top">
				<div class="wp">
					<div class="fl">
                        <p>联系方式：<b>3333333333</b></p>
                    </div>
                    <a style="color:white" class="fr registerbtn" href="register.html">注册</a>
                    <a style="color:white" class="fr loginbtn" href="login.html">登录</a>
				</div>
			</div>
            
            
    <div class="middle companyheader">
        <div class="wp">
            <img class="fl" style="width: 112px;height: 103px" src="../media/org/2016/11/imooc.png"/>
            <div class="head fl">
                <h1>
                    慕课网
                    <img src="../images/authentication.png"/>
                    <img src="../images/gold.png"/>
                </h1>
                <p class="fl">
                    <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                    <span class="precision company-credit" data-star-scope="5.0"></span>
                    <span class="key">5.0</span>
                </p>
            </div>
            <div class="btn fr collectionbtn  notlogin 
                 "data-favid="22" data-fav-type="1">
                 收藏
            </div>

        </div>
    </div>
			</div>
    </header>
</section>
<section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="index.html">首页</a>></li>
			<li><a href="org-list.html">课程机构</a>></li>
			<li>机构介绍</li>
		</ul>
	</div>
</section>

<section>
	<div class="wp list personal_list comp">
		<div class="left">
			<ul>
				<li class=""><a href="{% url 'org:detail_homepage' org_id %}">机构首页</a></li>
                <li class=""><a href="{% url 'org:detail_course' org_id %}">机构课程</a></li>
                <li class="active2"><a href="{% url 'org:detail_desc' org_id %}">机构介绍</a></li>
                <li class=""><a href="{% url 'org:detail_teachers' org_id %}">机构讲师</a></li>
			</ul>
		</div>
    
<div class="right companycenter layout" >
        <div class="head">
            <h1>机构介绍</h1>
        </div>
        <div class="des">
            
            <p><p>&nbsp; &nbsp;</p><h1 class="ue_t" label="Title center" name="tc" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;text-align:center;margin:0px 0px 20px;"><span style="color:#c0504d;">[键入文档标题]</span></h1><p style="text-align:center;"><strong class="ue_t">[键入文档副标题]</strong></p><h3><span class="ue_t" style="font-family:幼圆">[标题 1]</span></h3><p class="ue_t" style="text-indent:2em;">对于“插入”选项卡上的库，在设计时都充分考虑了其中的项与文档整体外观的协调性。 您可以使用这些库来插入表格、页眉、页脚、列表、封面以及其他文档构建基块。 您创建的图片、图表或关系图也将与当前的文档外观协调一致。</p><p class="ue_t" style="text-indent:2em;"><img src="../media/courses/ueditor/57aa86a0000145c512000460_20161210234050_865.jpg" title="" alt="57aa86a0000145c512000460.jpg"/> </p><h3><span class="ue_t" style="font-family:幼圆">[标题 2]</span></h3><p><img src="http://api.map.baidu.com/staticimage?center=116.410899,39.863624&zoom=11&width=530&height=340&markers=116.404,39.915" width="530" height="340"/> </p><p class="ue_t" style="text-indent:2em;">在“开始”选项卡上，通过从快速样式库中为所选文本选择一种外观，您可以方便地更改文档中所选文本的格式。 您还可以使用“开始”选项卡上的其他控件来直接设置文本格式。大多数控件都允许您选择是使用当前主题外观，还是使用某种直接指定的格式。</p><h3><span class="ue_t" style="font-family:幼圆">[标题 3]</span></h3><p>2016-12-10</p><p class="ue_t">对于“插入”选项卡上的库，在设计时都充分考虑了其中的项与文档整体外观的协调性。 您可以使用这些库来插入表格、页眉、页脚、列表、封面以及其他文档构建基块。 您创建的图片、图表或关系图也将与当前的文档外观协调一致。</p><p class="ue_t"><br/> </p><p><br/></p><p><br/></p></p>
            
        </div>
    </div>


</section>
<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->
<!--header start-->

<!--弹出省省市-->
<script src="{%static 'js/selectUi.js'%}" type='text/javascript'></script>
<script type="text/javascript" src="{%static 'js/plugins/laydate/laydate.js'%}"></script>
<script src="{%static 'js/plugins/layer/layer.js'%}"></script>
<script src="{%static 'js/plugins/queryCity/js/public.js'%}" type="text/javascript"></script>

<script type="text/javascript" src="{%static 'js/plugins/jquery.raty.js'%}.js"></script>
<script type="text/javascript">
    //收藏分享
//收藏分享
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"/org/add_fav/",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "5I2SlleZJOMUX9QbwYLUIAOshdrdpRcy");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="login.html";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}

$('.collectionbtn').on('click', function(){
    add_fav($(this), 1, 2);
});

$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path		: '../images/',
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg  : '暂时还未获得评价！',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);

    $('.jsFavBtn').on('click', function(){
        var type = $(this).attr('data-fav-type');
        if(type == '1'){
            favPraise($(this), 'fav' ,1 , '收藏');

        }else if(type == '3'){
            favPraise($(this), 'fav' ,3 );

        }else if(type == '11'){
            favPraise($(this), 'pra', 1);

        }else if(type == '4'){
            favPraise($(this), 'fav' ,4 );

        }
    });
})
</script>


<script type="text/javascript">
$(function() {
    $('.recordbtn1').click(function(){
        $('.recordbox1').show();
    });
    $('.recordbtn2').click(function(){
        $('.recordbox2').show();
    });

    $('.imgslide').unslider({
        speed: 500,               //  The speed to animate each slide (in milliseconds)
        delay: 3000,              //  The delay between slide animations (in milliseconds)
        complete: function() {},  //  A function that gets called after every slide animation
        keys: true,               //  Enable keyboard (left, right) arrow shortcuts
        dots: true,               //  Display dot navigation
        fluid: false              //  Support responsive design. May break non-responsive designs
    });
    var unslider = $('.imgslide').unslider();
    $('.unslider-arrow').click(function() {
        var fn = this.className.split(' ')[1];
        unslider.data('unslider')[fn]();
    });
});
</script>

</body>
</html>

hzj_test/templates/org-detail-teachers.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>机构首页</title>
	<link rel="stylesheet" type="text/css" href="{%static 'css/reset.css'%}">
	<link rel="stylesheet" type="text/css" href="{%static 'css/animate.css'%}">
	<link rel="stylesheet" type="text/css" href="{%static 'css/style.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'js/plugins/queryCity/css/cityLayout.css'%}">

    <script src="{%static 'js/jquery.min.js'%}.js" type="text/javascript"></script>
    <script src="{%static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    
</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
		<div  class="header2 header">
 			
                <div class="top">
				<div class="wp">
					<div class="fl">
                        <p>联系方式：<b>3333333333</b></p>
                    </div>
                    <a style="color:white" class="fr registerbtn" href="register.html">注册</a>
                    <a style="color:white" class="fr loginbtn" href="login.html">登录</a>
				</div>
			</div>
            
            
    <div class="middle companyheader">
        <div class="wp">
            <img class="fl" style="width: 112px;height: 103px" src="../media/org/2016/11/imooc.png"/>
            <div class="head fl">
                <h1>
                    慕课网
                    <img src="../images/authentication.png"/>
                    <img src="../images/gold.png"/>
                </h1>
                <p class="fl">
                    <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                    <span class="precision company-credit" data-star-scope="5.0"></span>
                    <span class="key">5.0</span>
                </p>
            </div>
            <div class="btn fr collectionbtn  notlogin 
                 "data-favid="22" data-fav-type="1">
                 收藏
            </div>

        </div>
    </div>
			</div>
    </header>
</section>
<section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="index.html">首页</a>></li>
			<li><a href="org-list.html">课程机构</a>></li>
			<li>机构教师</li>
		</ul>
	</div>
</section>

<section>
	<div class="wp list personal_list comp">
		<div class="left">
			<ul>
				<li class=""><a href="{% url 'org:detail_homepage'  org_id%}">机构首页</a></li>
                <li class=""><a href="{% url 'org:detail_course' org_id %}">机构课程</a></li>
                <li class=""><a href="{% url 'org:detail_desc' org_id %}">机构介绍</a></li>
                <li class="active2"><a href="{% url 'org:detail_teachers' org_id %}">机构讲师</a></li>
			</ul>
		</div>
    
<div class="right companycenter layout" >
        <div class="head">
            <h1>机构讲师</h1>
        </div>
        <div class="messagelist">
            <div class=" butler_list butler-fav-box">
                
                <dl class="des users">
                    <dt>
                        <a href="">
                        <img width="100" height="100" class="scrollLoading" data-url="../media/teacher/2016/11/aobama_CXWwMef.png" src="../media/teacher/2016/11/aobama_CXWwMef.png"/>
                        </a>
                    </dt>
                    <dd>
                        <h1>
                            <a href="">
                            bobby<span class="key">已认证</span>
                            </a>
                        </h1>
                        <ul class="cont clearfix">
                            <li class="time">工作年限：<span>5年</span></li>
                            <li class="c7">课程数：<span>3</span></li>
                        </ul>
                    </dd>
                </dl>
                
                <dl class="des users">
                    <dt>
                        <a href="">
                        <img width="100" height="100" class="scrollLoading" data-url="../media/teacher/2016/11/aobama.png" src="../media/teacher/2016/11/aobama.png"/>
                        </a>
                    </dt>
                    <dd>
                        <h1>
                            <a href="">
                            还是bobby<span class="key">已认证</span>
                            </a>
                        </h1>
                        <ul class="cont clearfix">
                            <li class="time">工作年限：<span>5年</span></li>
                            <li class="c7">课程数：<span>3</span></li>
                        </ul>
                    </dd>
                </dl>
                

            </div>
        </div>
    </div>


</section>
<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->
<!--header start-->

<!--弹出省省市-->
<<script src="{%static 'js/selectUi.js'%}" type='text/javascript'></script>
<script type="text/javascript" src="{%static 'js/plugins/laydate/laydate.js'%}"></script>
<script src="{%static 'js/plugins/layer/layer.js'%}"></script>
<script src="{%static 'js/plugins/queryCity/js/public.js'%}" type="text/javascript"></script>

<script type="text/javascript" src="{%static 'js/plugins/jquery.raty.js'%}.js"></script>
<script type="text/javascript">
    //收藏分享
//收藏分享
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"/org/add_fav/",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "5I2SlleZJOMUX9QbwYLUIAOshdrdpRcy");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="login.html";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}

$('.collectionbtn').on('click', function(){
    add_fav($(this), 1, 2);
});

$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path		: '../images/',
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg  : '暂时还未获得评价！',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);

    $('.jsFavBtn').on('click', function(){
        var type = $(this).attr('data-fav-type');
        if(type == '1'){
            favPraise($(this), 'fav' ,1 , '收藏');

        }else if(type == '3'){
            favPraise($(this), 'fav' ,3 );

        }else if(type == '11'){
            favPraise($(this), 'pra', 1);

        }else if(type == '4'){
            favPraise($(this), 'fav' ,4 );

        }
    });
})
</script>


<script type="text/javascript">
$(function() {
    $('.recordbtn1').click(function(){
        $('.recordbox1').show();
    });
    $('.recordbtn2').click(function(){
        $('.recordbox2').show();
    });

    $('.imgslide').unslider({
        speed: 500,               //  The speed to animate each slide (in milliseconds)
        delay: 3000,              //  The delay between slide animations (in milliseconds)
        complete: function() {},  //  A function that gets called after every slide animation
        keys: true,               //  Enable keyboard (left, right) arrow shortcuts
        dots: true,               //  Display dot navigation
        fluid: false              //  Support responsive design. May break non-responsive designs
    });
    var unslider = $('.imgslide').unslider();
    $('.unslider-arrow').click(function() {
        var fn = this.className.split(' ')[1];
        unslider.data('unslider')[fn]();
    });
});
</script>

</body>
</html>

hzj_test/templates/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title>密码修改</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/animate.css">
	<link rel="stylesheet" type="text/css" href="/static/css/style.css">

<body>
<div class="wp">
    <div class="resetpassword" id="resetPwdForm">
        <h1>修改密码</h1>
        <p>已经通过验证，请设置新密码</p>
        <form id="reset_password_form" action="" method="post">
            <ul>
                <li>
                    <span class="">新 密 码 ：</span>
                    <input type="password" name="password" id="pwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <li>
                    <span class="">确定密码：</span>
                    <input type="password" name="password2" id="repwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <li class="button">
                    <input type="button" value="提交" onclick="reset_password_form_submit()">
                </li>
            </ul>
        </form>
    </div>
    <div class="resetpassword" id="reset_password_tips" style="display:none;">
        <h1>修改密码成功,请重新登录</h1>
        <img class="fl" src="/static/images/check2.png">
        <p class="successword">已经成功修改密码，请重新登录</p>
    </div>
</div>
</body>
</html>